const dicionario = {};

/* Última vez contado: 120 palavras */
const db = [
    { nome: 'Abacate', dica: 'Fruta' }, 
    { nome: 'Morango', dica: 'Fruta' }, 
    { nome: 'Escada', dica: 'Subir' }, 
    { nome: 'Criança', dica: 'Maternidade' }, 
    { nome: 'Fralda', dica: 'Bebê' }, 
    { nome: 'Leão', dica: 'Animal' }, 
    { nome: 'Pássaro', dica: 'Animal' }, 
    { nome: 'Natação', dica: 'Água' }, 
    { nome: 'Banho', dica: 'Ficar limpo' }, 
    { nome: 'Academia', dica: 'Força' }, 
    { nome: 'Faca', dica: 'Corta' }, 
    { nome: 'Banana', dica: 'Fruta' }, 
    { nome: 'Chave', dica: 'Porta' }, 
    { nome: 'Sapato', dica: 'Caminhar' }, 
    { nome: 'Relógio', dica: 'Tempo' }, 
    { nome: 'Bolsa', dica: 'Guardar' }, 
    { nome: 'Abraço'}, 
    { nome: 'Beijo', dica: 'Amor' }, 
    { nome: 'Flores', dica: 'Coloridas' }, 
    { nome: 'Bateria', dica: 'Carga' }, 
    { nome: 'Carro', dica: 'Veículo' }, 
    { nome: 'Moto', dica: 'Veículo' }, 
    { nome: 'Colar', dica: 'Joalheria' }, 
    { nome: 'Brinco', dica: 'Joalheria' }, 
    { nome: 'Casa'}, 
    { nome: 'Igreja', dica: 'Religião' }, 
    { nome: 'Macaco', dica: 'Animal' }, 
    { nome: 'Chá', dica: 'Reino Unido' }, 
    { nome: 'Dançar'}, 
    { nome: 'Sol', dica: 'Calor' }, 
    { nome: 'Árvore'}, 
    { nome: 'Música'}, 
    { nome: 'Pizza', dica: 'Comida Redonda' }, 
    { nome: 'Sorvete', dica: 'Gelado' }, 
    { nome: 'Ônibus', dica: 'Meio de Transporte' }, 
    { nome: 'Maçã', dica: 'Vermelho' }, 
    { nome: 'Espelho', dica: 'Prata' }, 
    { nome: 'Guitarra', dica: 'Rock' }, 
    { nome: 'Livro', dica: 'Papel' }, 
    { nome: 'Estrela', dica: 'Céu' }, 
    { nome: 'Balão', dica: 'Usa ar quente para subir' }, 
    { nome: 'Avião', dica: 'Voo' }, 
    { nome: 'Elefante', dica: 'Grande' }, 
    { nome: 'Bola', dica: 'Redonda' }, 
    { nome: 'Bebê', dica: 'Maternidade' }, 
    { nome: 'Peixe', dica: 'Mar ou rio' }, 
    { nome: 'Futebol', dica: 'Bola' }, 
    { nome: 'Toalha', dica: 'Quanto mais seca, mais molhado fica' }, 
    { nome: 'Papel higiênico', dica: 'Banheiro' }, 
    { nome: 'Basquete', dica: 'Bola' }, 
    { nome: 'Controle remoto', dica: 'TV' }, 
    { nome: 'Triste'}, 
    { nome: 'Gato', dica: 'Animal' }, 
    { nome: 'Golfe', dica: 'Esporte' }, 
    { nome: 'Tesoura', dica: 'Pedra, Papel...' }, 
    { nome: 'Colher', dica: 'Doces/Sopa' }, 
    { nome: 'Pular', dica: 'Saltar' }, 
    { nome: 'Galinha', dica: 'Ovo' }, 
    { nome: 'Sapo', dica: 'Lago' }, 
    { nome: 'Espirro', dica: 'Saúde!' }, 
    { nome: 'Martelo', dica: 'Prego' }, 
    { nome: 'Violão', dica: 'Instrumento Musical' }, 
    { nome: 'Aplaudir'}, 
    { nome: 'Tosse'}, 
    { nome: 'Chifres', dica: 'Corno' }, 
    { nome: 'Pinguins', dica: 'Os ... de Madagascar' }, 
    { nome: 'Chorar', dica: 'Tristeza' }, 
    { nome: 'Rabo'}, 
    { nome: 'Piada', dica: 'Engraçado' }, 
    { nome: 'Escova de dente', dica: 'Higiene' }, 
    { nome: 'Celular'}, 
    { nome: 'Cachorro', dica: 'Amigo Fiel' }, 
    { nome: 'Pato', dica: 'Animal que pode Voar e Nadar' }, 
    { nome: 'Sofá', dica: 'Sentar' }, 
    { nome: 'Fotógrafo', dica: 'Câmera' }, 
    { nome: 'Óculos', dica: 'Visão' }, 
    { nome: 'Balé', dica: 'Dança' }, 
    { nome: 'Pipa'}, 
    { nome: 'Café', dica: 'Acordar' }, 
    { nome: 'Táxi', dica: 'Uber' }, 
    { nome: 'Cadeira'}, 
    { nome: 'Elevador', dica: 'Andares' }, 
    { nome: 'Bicicleta', dica: 'Veículo' }, 
    { nome: 'Fogão', dica: 'Quente' }, 
    { nome: 'Copo', dica: 'Bebidas' }, 
    { nome: 'Orelhas', dica: 'Audição' }, 
    { nome: 'Chocolate', dica: 'A Fantástica Fábrica' }, 
    { nome: 'Pescador', dica: 'Varinha' }, 
    { nome: 'Notebook', dica: 'Portátil' }, 
    { nome: 'Lápis', dica: 'Escrita' }, 
    { nome: 'JavaScript', dica: 'Linguagem de Programação' }, 
    { nome: 'HTML', dica: 'Linguagem da Internet' }, 
    { nome: 'CSS', dica: 'Cascata' }, 
    { nome: 'Internet', dica: 'O "i" do IPhone' }, 
    { nome: 'WWW', dica: 'Rede Mundial' }, 
    { nome: 'Google', dica: 'Pesquisas' }, 
    { nome: 'ChatGPT', dica: 'Inteligência Artificial' }, 
    { nome: 'Python', dica: 'Linguagem de Programação' }, 
    { nome: 'Programação'}, 
    { nome: 'Jogos', dica: 'Mais legal com amigos' }, 
    { nome: 'VS Code', dica: 'Editor de Código' }, 
    { nome: 'Chrome', dica: 'Navegador Web' }, 
    { nome: 'FireFox', dica: 'Navegador Web' }, 
    { nome: 'Microsoft', dica: 'Windows' }, 
    { nome: 'Apple', dica: 'Caro' }, 
    { nome: 'Windows', dica: 'Sistema Operacional' }, 
    { nome: 'Algoritmo', dica: 'Sequência de eventos' }, 
    { nome: 'Nuvem', dica: 'Chuva' }, 
    { nome: 'Linux', dica: 'Inimigo do Windows' }, 
    { nome: 'Hardware', dica: 'Computadores' }, 
    { nome: 'Software', dica: 'Computadores' }, 
    { nome: 'Java', dica: 'Linguagem de Programação' }, 
    { nome: 'Bug', dica: 'Problema no Computador/Programa' }, 
    { nome: 'Antivírus', dica: 'Proteção' }, 
    { nome: 'Backup', dica: 'Salvar' }, 
    { nome: 'Bluetooth', dica: 'Conexão sem Fio' }, 
    { nome: 'Computador'}, 
    { nome: 'Endereço IP', dica: 'Redes de Computadores' }, 
    { nome: 'VPN', dica: 'Conexão Privada' }, 
    { nome: 'Wi-Fi', dica: 'Conexão sem Fio' }
];

/* Template do Dicionário

const db = [
    { nome: 'abacate', dica: 'fruta'},
    { nome: '', dica:''}, 
    { nome: ''}, 
    { nome: ''}
];
*/

console.log(db.length+' palavras salvas no dicionário');

dicionario.getPalavra = function () {
    const numAleat = Math.floor(Math.random() * db.length);
    return db[numAleat];
};

export { dicionario as default };